**Pandas is a Python library used for working with data. It helps us store, clean, analyze, and manipulate structured data easily**

**There are two core objects in pandas: the DataFrame and the Series.**

  A Pandas DataFrame is a two-dimensional table-like structure in Python where data is arranged in rows and columns. It’s one of the most commonly used tools for handling data and makes it easy to organize, analyze and manipulate data. It can store different types of data such as numbers, text and dates across its columns. The main parts of a DataFrame are:

Data: Actual values in the table.

Rows: Labels that identify each row.

Columns: Labels that define each data category.

        Name    Marks
    0   Asha     85
    1  Rahul     90
    2   John     78

In [515]:
import pandas as pd
df= pd.read_csv("/content/students.csv")
df

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,1001.0,Aarav,18.0,Mysuru,85.0,82.0,88.0,92.0
1,1002.0,Diya,19.0,Bengaluru,92.0,89.0,94.0,96.0
2,1003.0,Arjun,18.0,Dharwad,76.0,74.0,79.0,88.0
3,1004.0,Ananya,20.0,Belagavi,NaN,91.0,85.0,94.0
4,1005.0,Rohan,19.0,Mangaluru,69.0,71.0,73.0,81.0
5,1006.0,Ishita,18.0,Hubballi,95.0,93.0,96.0,98.0
6,1007.0,Vivek,21.0,Mysuru,81.0,79.0,84.0,90.0
7,1008.0,Sneha,19.0,NaN,73.0,77.0,70.0,85.0
8,1009.0,Karan,20.0,Shivamogga,90.0,88.0,92.0,95.0
9,1010.0,Meera,18.0,Udupi,84.0,86.0,87.0,91.0
10,1011.0,Aditya,22.0,Tumakuru,78.0,81.0,80.0,87.0
11,1012.0,Pooja,19.0,Mysuru,91.0,NaN,93.0,97.0
12,1013.0,Rahul,20.0,Bengaluru,67.0,69.0,71.0,79.0
13,1014.0,Kavya,18.0,Belagavi,86.0,84.0,89.0,93.0
14,1015.0,Nikhil,21.0,Dharwad,72.0,75.0,76.0,84.0
15,1016.0,Priya,19.0,Mangaluru,94.0,92.0,91.0,96.0
16,1017.0,Sanjay,22.0,Hubballi,80.0,78.0,82.0,NaN
17,1018.0,Neha,20.0,Mysuru,75.0,73.0,78.0,86.0
18,1019.0,Varun,18.0,Udupi,89.0,91.0,90.0,94.0
19,1020.0,Aisha,21.0,Bengaluru,83.0,85.0,88.0,90.0
20,1021.0,Manoj,NaN,Tumakuru,70.0,72.0,74.0,82.0
21,1022.0,Riya,20.0,Shivamogga,96.0,94.0,95.0,99.0
22,1023.0,Akash,18.0,Belagavi,87.0,88.0,85.0,92.0
23,1024.0,Shreya,22.0,Mangaluru,79.0,76.0,NaN,88.0
24,1025.0,Yash,19.0,Mysuru,93.0,90.0,92.0,97.0
25,1005.0,Rohan,19.0,Mangaluru,69.0,71.0,73.0,81.0
26,1012.0,Pooja,19.0,Mysuru,91.0,NaN,93.0,97.0
27,1019.0,Varun,18.0,Udupi,89.0,91.0,90.0,94.0
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [516]:
df.head(5)

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,1001.0,Aarav,18.0,Mysuru,85.0,82.0,88.0,92.0
1,1002.0,Diya,19.0,Bengaluru,92.0,89.0,94.0,96.0
2,1003.0,Arjun,18.0,Dharwad,76.0,74.0,79.0,88.0
3,1004.0,Ananya,20.0,Belagavi,NaN,91.0,85.0,94.0
4,1005.0,Rohan,19.0,Mangaluru,69.0,71.0,73.0,81.0

In [517]:
df.tail(5)

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
24,1025.0,Yash,19.0,Mysuru,93.0,90.0,92.0,97.0
25,1005.0,Rohan,19.0,Mangaluru,69.0,71.0,73.0,81.0
26,1012.0,Pooja,19.0,Mysuru,91.0,NaN,93.0,97.0
27,1019.0,Varun,18.0,Udupi,89.0,91.0,90.0,94.0
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [518]:
df.shape

(29, 8)

In [519]:
df.columns

Index(['student_id', 'name', 'age', 'city', 'python_marks', 'sql_marks',
       'pandas_marks', 'attendance'],
      dtype='object')

In [520]:
df.dtypes

student_id      float64
name             object
age             float64
city             object
python_marks    float64
sql_marks       float64
pandas_marks    float64
attendance      float64
dtype: object

In [521]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    28 non-null     float64
 1   name          28 non-null     object
 2   age           27 non-null     float64
 3   city          27 non-null     object
 4   python_marks  27 non-null     float64
 5   sql_marks     26 non-null     float64
 6   pandas_marks  27 non-null     float64
 7   attendance    27 non-null     float64
dtypes: float64(6), object(2)
memory usage: 1.9+ KB

In [522]:
df.describe()

,student_id,age,python_marks,sql_marks,pandas_marks,attendance
count,28.000000,27.000000,27.000000,26.000000,27.000000,27.000000
mean,1012.892857,19.444444,82.740741,82.307692,84.740741,90.592593
std,7.202568,1.339728,8.981145,8.028794,8.041204,5.839252
min,1001.000000,18.000000,67.000000,69.000000,70.000000,79.000000
25%,1006.750000,18.000000,75.500000,75.250000,78.500000,86.500000
50%,1012.500000,19.000000,84.000000,83.000000,87.000000,92.000000
75%,1019.000000,20.000000,90.500000,89.750000,91.500000,95.500000
max,1025.000000,22.000000,96.000000,94.000000,96.000000,99.000000

In [523]:
df.isnull().sum()

student_id      1
name            1
age             2
city            2
python_marks    2
sql_marks       3
pandas_marks    2
attendance      2
dtype: int64

In [524]:
cols=['age','python_marks','sql_marks','pandas_marks','attendance']
df[cols]= df[cols].fillna(df[cols].mean())

In [525]:
df['city']=df['city'].fillna("None")
df['name']=df['name'].fillna("None")

In [526]:
df.isnull().sum()

student_id      1
name            0
age             0
city            0
python_marks    0
sql_marks       0
pandas_marks    0
attendance      0
dtype: int64

In [527]:
df.duplicated().sum()

np.int64(3)

In [528]:
df.drop_duplicates(inplace=True)

In [529]:
df.duplicated().sum()

np.int64(0)

In [530]:
print("Average Python Marks:", df['python_marks'].mean().round(2))

Average Python Marks: 82.71

In [531]:
print("Average SQL Marks:", df['sql_marks'].mean().round(2))

Average SQL Marks: 82.41

In [532]:
print("Average Pandas Marks:", df['pandas_marks'].mean().round(2))

Average Pandas Marks: 84.67

In [533]:
print("Maximum Python Marks:", df['python_marks'].max())
print("Minimum Python Marks:", df['python_marks'].min())

Maximum Python Marks: 96.0
Minimum Python Marks: 67.0

In [534]:
print("Maximum SQL Marks:", df['sql_marks'].max())
print("Minimum SQL Marks:", df['sql_marks'].min())

Maximum SQL Marks: 94.0
Minimum SQL Marks: 69.0

In [535]:
print("Maximum Pandas Marks:", df['pandas_marks'].max())
print("Minimum Pandas Marks:", df['pandas_marks'].min())

Maximum Pandas Marks: 96.0
Minimum Pandas Marks: 70.0

In [536]:
df.sort_values(by='python_marks',ascending=False)

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
21,1022.0,Riya,20.000000,Shivamogga,96.000000,94.000000,95.000000,99.000000
5,1006.0,Ishita,18.000000,Hubballi,95.000000,93.000000,96.000000,98.000000
15,1016.0,Priya,19.000000,Mangaluru,94.000000,92.000000,91.000000,96.000000
24,1025.0,Yash,19.000000,Mysuru,93.000000,90.000000,92.000000,97.000000
1,1002.0,Diya,19.000000,Bengaluru,92.000000,89.000000,94.000000,96.000000
11,1012.0,Pooja,19.000000,Mysuru,91.000000,82.307692,93.000000,97.000000
8,1009.0,Karan,20.000000,Shivamogga,90.000000,88.000000,92.000000,95.000000
18,1019.0,Varun,18.000000,Udupi,89.000000,91.000000,90.000000,94.000000
22,1023.0,Akash,18.000000,Belagavi,87.000000,88.000000,85.000000,92.000000
13,1014.0,Kavya,18.000000,Belagavi,86.000000,84.000000,89.000000,93.000000
0,1001.0,Aarav,18.000000,Mysuru,85.000000,82.000000,88.000000,92.000000
9,1010.0,Meera,18.000000,Udupi,84.000000,86.000000,87.000000,91.000000
19,1020.0,Aisha,21.000000,Bengaluru,83.000000,85.000000,88.000000,90.000000
28,NaN,None,19.444444,None,82.740741,82.307692,84.740741,90.592593
3,1004.0,Ananya,20.000000,Belagavi,82.740741,91.000000,85.000000,94.000000
6,1007.0,Vivek,21.000000,Mysuru,81.000000,79.000000,84.000000,90.000000
16,1017.0,Sanjay,22.000000,Hubballi,80.000000,78.000000,82.000000,90.592593
23,1024.0,Shreya,22.000000,Mangaluru,79.000000,76.000000,84.740741,88.000000
10,1011.0,Aditya,22.000000,Tumakuru,78.000000,81.000000,80.000000,87.000000
2,1003.0,Arjun,18.000000,Dharwad,76.000000,74.000000,79.000000,88.000000
17,1018.0,Neha,20.000000,Mysuru,75.000000,73.000000,78.000000,86.000000
7,1008.0,Sneha,19.000000,None,73.000000,77.000000,70.000000,85.000000
14,1015.0,Nikhil,21.000000,Dharwad,72.000000,75.000000,76.000000,84.000000
20,1021.0,Manoj,19.444444,Tumakuru,70.000000,72.000000,74.000000,82.000000
4,1005.0,Rohan,19.000000,Mangaluru,69.000000,71.000000,73.000000,81.000000
12,1013.0,Rahul,20.000000,Bengaluru,67.000000,69.000000,71.000000,79.000000

In [537]:
df.sort_values(by='attendance',ascending=False)

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
21,1022.0,Riya,20.000000,Shivamogga,96.000000,94.000000,95.000000,99.000000
5,1006.0,Ishita,18.000000,Hubballi,95.000000,93.000000,96.000000,98.000000
11,1012.0,Pooja,19.000000,Mysuru,91.000000,82.307692,93.000000,97.000000
24,1025.0,Yash,19.000000,Mysuru,93.000000,90.000000,92.000000,97.000000
15,1016.0,Priya,19.000000,Mangaluru,94.000000,92.000000,91.000000,96.000000
1,1002.0,Diya,19.000000,Bengaluru,92.000000,89.000000,94.000000,96.000000
8,1009.0,Karan,20.000000,Shivamogga,90.000000,88.000000,92.000000,95.000000
3,1004.0,Ananya,20.000000,Belagavi,82.740741,91.000000,85.000000,94.000000
18,1019.0,Varun,18.000000,Udupi,89.000000,91.000000,90.000000,94.000000
13,1014.0,Kavya,18.000000,Belagavi,86.000000,84.000000,89.000000,93.000000
22,1023.0,Akash,18.000000,Belagavi,87.000000,88.000000,85.000000,92.000000
0,1001.0,Aarav,18.000000,Mysuru,85.000000,82.000000,88.000000,92.000000
9,1010.0,Meera,18.000000,Udupi,84.000000,86.000000,87.000000,91.000000
16,1017.0,Sanjay,22.000000,Hubballi,80.000000,78.000000,82.000000,90.592593
28,NaN,None,19.444444,None,82.740741,82.307692,84.740741,90.592593
19,1020.0,Aisha,21.000000,Bengaluru,83.000000,85.000000,88.000000,90.000000
6,1007.0,Vivek,21.000000,Mysuru,81.000000,79.000000,84.000000,90.000000
2,1003.0,Arjun,18.000000,Dharwad,76.000000,74.000000,79.000000,88.000000
23,1024.0,Shreya,22.000000,Mangaluru,79.000000,76.000000,84.740741,88.000000
10,1011.0,Aditya,22.000000,Tumakuru,78.000000,81.000000,80.000000,87.000000
17,1018.0,Neha,20.000000,Mysuru,75.000000,73.000000,78.000000,86.000000
7,1008.0,Sneha,19.000000,None,73.000000,77.000000,70.000000,85.000000
14,1015.0,Nikhil,21.000000,Dharwad,72.000000,75.000000,76.000000,84.000000
20,1021.0,Manoj,19.444444,Tumakuru,70.000000,72.000000,74.000000,82.000000
4,1005.0,Rohan,19.000000,Mangaluru,69.000000,71.000000,73.000000,81.000000
12,1013.0,Rahul,20.000000,Bengaluru,67.000000,69.000000,71.000000,79.000000

In [538]:
# Filter students having Python marks greater than 80.
df[df['python_marks'] >80]

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,1001.0,Aarav,18.000000,Mysuru,85.000000,82.000000,88.000000,92.000000
1,1002.0,Diya,19.000000,Bengaluru,92.000000,89.000000,94.000000,96.000000
3,1004.0,Ananya,20.000000,Belagavi,82.740741,91.000000,85.000000,94.000000
5,1006.0,Ishita,18.000000,Hubballi,95.000000,93.000000,96.000000,98.000000
6,1007.0,Vivek,21.000000,Mysuru,81.000000,79.000000,84.000000,90.000000
8,1009.0,Karan,20.000000,Shivamogga,90.000000,88.000000,92.000000,95.000000
9,1010.0,Meera,18.000000,Udupi,84.000000,86.000000,87.000000,91.000000
11,1012.0,Pooja,19.000000,Mysuru,91.000000,82.307692,93.000000,97.000000
13,1014.0,Kavya,18.000000,Belagavi,86.000000,84.000000,89.000000,93.000000
15,1016.0,Priya,19.000000,Mangaluru,94.000000,92.000000,91.000000,96.000000
18,1019.0,Varun,18.000000,Udupi,89.000000,91.000000,90.000000,94.000000
19,1020.0,Aisha,21.000000,Bengaluru,83.000000,85.000000,88.000000,90.000000
21,1022.0,Riya,20.000000,Shivamogga,96.000000,94.000000,95.000000,99.000000
22,1023.0,Akash,18.000000,Belagavi,87.000000,88.000000,85.000000,92.000000
24,1025.0,Yash,19.000000,Mysuru,93.000000,90.000000,92.000000,97.000000
28,NaN,None,19.444444,None,82.740741,82.307692,84.740741,90.592593

In [539]:
# Filter students having attendance greater than 75.
df[df['attendance']>75]

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,1001.0,Aarav,18.000000,Mysuru,85.000000,82.000000,88.000000,92.000000
1,1002.0,Diya,19.000000,Bengaluru,92.000000,89.000000,94.000000,96.000000
2,1003.0,Arjun,18.000000,Dharwad,76.000000,74.000000,79.000000,88.000000
3,1004.0,Ananya,20.000000,Belagavi,82.740741,91.000000,85.000000,94.000000
4,1005.0,Rohan,19.000000,Mangaluru,69.000000,71.000000,73.000000,81.000000
5,1006.0,Ishita,18.000000,Hubballi,95.000000,93.000000,96.000000,98.000000
6,1007.0,Vivek,21.000000,Mysuru,81.000000,79.000000,84.000000,90.000000
7,1008.0,Sneha,19.000000,None,73.000000,77.000000,70.000000,85.000000
8,1009.0,Karan,20.000000,Shivamogga,90.000000,88.000000,92.000000,95.000000
9,1010.0,Meera,18.000000,Udupi,84.000000,86.000000,87.000000,91.000000
10,1011.0,Aditya,22.000000,Tumakuru,78.000000,81.000000,80.000000,87.000000
11,1012.0,Pooja,19.000000,Mysuru,91.000000,82.307692,93.000000,97.000000
12,1013.0,Rahul,20.000000,Bengaluru,67.000000,69.000000,71.000000,79.000000
13,1014.0,Kavya,18.000000,Belagavi,86.000000,84.000000,89.000000,93.000000
14,1015.0,Nikhil,21.000000,Dharwad,72.000000,75.000000,76.000000,84.000000
15,1016.0,Priya,19.000000,Mangaluru,94.000000,92.000000,91.000000,96.000000
16,1017.0,Sanjay,22.000000,Hubballi,80.000000,78.000000,82.000000,90.592593
17,1018.0,Neha,20.000000,Mysuru,75.000000,73.000000,78.000000,86.000000
18,1019.0,Varun,18.000000,Udupi,89.000000,91.000000,90.000000,94.000000
19,1020.0,Aisha,21.000000,Bengaluru,83.000000,85.000000,88.000000,90.000000
20,1021.0,Manoj,19.444444,Tumakuru,70.000000,72.000000,74.000000,82.000000
21,1022.0,Riya,20.000000,Shivamogga,96.000000,94.000000,95.000000,99.000000
22,1023.0,Akash,18.000000,Belagavi,87.000000,88.000000,85.000000,92.000000
23,1024.0,Shreya,22.000000,Mangaluru,79.000000,76.000000,84.740741,88.000000
24,1025.0,Yash,19.000000,Mysuru,93.000000,90.000000,92.000000,97.000000
28,NaN,None,19.444444,None,82.740741,82.307692,84.740741,90.592593

In [540]:
# Select only name, python_marks, and pandas_marks.
df[['name','python_marks','pandas_marks']]

      name  python_marks  pandas_marks
0    Aarav     85.000000     88.000000
1     Diya     92.000000     94.000000
2    Arjun     76.000000     79.000000
3   Ananya     82.740741     85.000000
4    Rohan     69.000000     73.000000
5   Ishita     95.000000     96.000000
6    Vivek     81.000000     84.000000
7    Sneha     73.000000     70.000000
8    Karan     90.000000     92.000000
9    Meera     84.000000     87.000000
10  Aditya     78.000000     80.000000
11   Pooja     91.000000     93.000000
12   Rahul     67.000000     71.000000
13   Kavya     86.000000     89.000000
14  Nikhil     72.000000     76.000000
15   Priya     94.000000     91.000000
16  Sanjay     80.000000     82.000000
17    Neha     75.000000     78.000000
18   Varun     89.000000     90.000000
19   Aisha     83.000000     88.000000
20   Manoj     70.000000     74.000000
21    Riya     96.000000     95.000000
22   Akash     87.000000     85.000000
23  Shreya     79.000000     84.740741
24    Yash     93.000000     92.000000
28    None     82.740741     84.740741

In [541]:
# Add a new column called total_marks.
df['total_marks']=(df['pandas_marks']+df['python_marks']+df['sql_marks']).round(2)

In [542]:
df['average_marks']=(df['total_marks']/3).round(2)

In [543]:
df.to_csv("final.csv")

In [544]:
df['python_marks']= df['python_marks'].fillna(df['python_marks'].mean())

In [545]:
# filtering
df[df['pandas_marks'] == df['pandas_marks'].max()]['name']

5    Ishita
Name: name, dtype: object

In [546]:
df.rename(columns={"name":"student_name"})

,student_id,student_name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks,average_marks
0,1001.0,Aarav,18.000000,Mysuru,85.000000,82.000000,88.000000,92.000000,255.00,85.00
1,1002.0,Diya,19.000000,Bengaluru,92.000000,89.000000,94.000000,96.000000,275.00,91.67
2,1003.0,Arjun,18.000000,Dharwad,76.000000,74.000000,79.000000,88.000000,229.00,76.33
3,1004.0,Ananya,20.000000,Belagavi,82.740741,91.000000,85.000000,94.000000,258.74,86.25
4,1005.0,Rohan,19.000000,Mangaluru,69.000000,71.000000,73.000000,81.000000,213.00,71.00
5,1006.0,Ishita,18.000000,Hubballi,95.000000,93.000000,96.000000,98.000000,284.00,94.67
6,1007.0,Vivek,21.000000,Mysuru,81.000000,79.000000,84.000000,90.000000,244.00,81.33
7,1008.0,Sneha,19.000000,None,73.000000,77.000000,70.000000,85.000000,220.00,73.33
8,1009.0,Karan,20.000000,Shivamogga,90.000000,88.000000,92.000000,95.000000,270.00,90.00
9,1010.0,Meera,18.000000,Udupi,84.000000,86.000000,87.000000,91.000000,257.00,85.67
10,1011.0,Aditya,22.000000,Tumakuru,78.000000,81.000000,80.000000,87.000000,239.00,79.67
11,1012.0,Pooja,19.000000,Mysuru,91.000000,82.307692,93.000000,97.000000,266.31,88.77
12,1013.0,Rahul,20.000000,Bengaluru,67.000000,69.000000,71.000000,79.000000,207.00,69.00
13,1014.0,Kavya,18.000000,Belagavi,86.000000,84.000000,89.000000,93.000000,259.00,86.33
14,1015.0,Nikhil,21.000000,Dharwad,72.000000,75.000000,76.000000,84.000000,223.00,74.33
15,1016.0,Priya,19.000000,Mangaluru,94.000000,92.000000,91.000000,96.000000,277.00,92.33
16,1017.0,Sanjay,22.000000,Hubballi,80.000000,78.000000,82.000000,90.592593,240.00,80.00
17,1018.0,Neha,20.000000,Mysuru,75.000000,73.000000,78.000000,86.000000,226.00,75.33
18,1019.0,Varun,18.000000,Udupi,89.000000,91.000000,90.000000,94.000000,270.00,90.00
19,1020.0,Aisha,21.000000,Bengaluru,83.000000,85.000000,88.000000,90.000000,256.00,85.33
20,1021.0,Manoj,19.444444,Tumakuru,70.000000,72.000000,74.000000,82.000000,216.00,72.00
21,1022.0,Riya,20.000000,Shivamogga,96.000000,94.000000,95.000000,99.000000,285.00,95.00
22,1023.0,Akash,18.000000,Belagavi,87.000000,88.000000,85.000000,92.000000,260.00,86.67
23,1024.0,Shreya,22.000000,Mangaluru,79.000000,76.000000,84.740741,88.000000,239.74,79.91
24,1025.0,Yash,19.000000,Mysuru,93.000000,90.000000,92.000000,97.000000,275.00,91.67
28,NaN,None,19.444444,None,82.740741,82.307692,84.740741,90.592593,249.79,83.26

In [547]:
df['city'].unique()

array(['Mysuru', 'Bengaluru', 'Dharwad', 'Belagavi', 'Mangaluru',
       'Hubballi', 'None', 'Shivamogga', 'Udupi', 'Tumakuru'],
      dtype=object)

In [548]:
# Filter students having Python marks greater than 80.
# df[df['python_marks'] >80]
# (df['python_marks'] >80).sum()
df[df['python_marks'] >80][['name','python_marks']]

      name  python_marks
0    Aarav     85.000000
1     Diya     92.000000
3   Ananya     82.740741
5   Ishita     95.000000
6    Vivek     81.000000
8    Karan     90.000000
9    Meera     84.000000
11   Pooja     91.000000
13   Kavya     86.000000
15   Priya     94.000000
18   Varun     89.000000
19   Aisha     83.000000
21    Riya     96.000000
22   Akash     87.000000
24    Yash     93.000000
28    None     82.740741

In [549]:
# Sort students by attendance.
df.sort_values(by='attendance',ascending=False)

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks,average_marks
21,1022.0,Riya,20.000000,Shivamogga,96.000000,94.000000,95.000000,99.000000,285.00,95.00
5,1006.0,Ishita,18.000000,Hubballi,95.000000,93.000000,96.000000,98.000000,284.00,94.67
11,1012.0,Pooja,19.000000,Mysuru,91.000000,82.307692,93.000000,97.000000,266.31,88.77
24,1025.0,Yash,19.000000,Mysuru,93.000000,90.000000,92.000000,97.000000,275.00,91.67
15,1016.0,Priya,19.000000,Mangaluru,94.000000,92.000000,91.000000,96.000000,277.00,92.33
1,1002.0,Diya,19.000000,Bengaluru,92.000000,89.000000,94.000000,96.000000,275.00,91.67
8,1009.0,Karan,20.000000,Shivamogga,90.000000,88.000000,92.000000,95.000000,270.00,90.00
3,1004.0,Ananya,20.000000,Belagavi,82.740741,91.000000,85.000000,94.000000,258.74,86.25
18,1019.0,Varun,18.000000,Udupi,89.000000,91.000000,90.000000,94.000000,270.00,90.00
13,1014.0,Kavya,18.000000,Belagavi,86.000000,84.000000,89.000000,93.000000,259.00,86.33
22,1023.0,Akash,18.000000,Belagavi,87.000000,88.000000,85.000000,92.000000,260.00,86.67
0,1001.0,Aarav,18.000000,Mysuru,85.000000,82.000000,88.000000,92.000000,255.00,85.00
9,1010.0,Meera,18.000000,Udupi,84.000000,86.000000,87.000000,91.000000,257.00,85.67
16,1017.0,Sanjay,22.000000,Hubballi,80.000000,78.000000,82.000000,90.592593,240.00,80.00
28,NaN,None,19.444444,None,82.740741,82.307692,84.740741,90.592593,249.79,83.26
19,1020.0,Aisha,21.000000,Bengaluru,83.000000,85.000000,88.000000,90.000000,256.00,85.33
6,1007.0,Vivek,21.000000,Mysuru,81.000000,79.000000,84.000000,90.000000,244.00,81.33
2,1003.0,Arjun,18.000000,Dharwad,76.000000,74.000000,79.000000,88.000000,229.00,76.33
23,1024.0,Shreya,22.000000,Mangaluru,79.000000,76.000000,84.740741,88.000000,239.74,79.91
10,1011.0,Aditya,22.000000,Tumakuru,78.000000,81.000000,80.000000,87.000000,239.00,79.67
17,1018.0,Neha,20.000000,Mysuru,75.000000,73.000000,78.000000,86.000000,226.00,75.33
7,1008.0,Sneha,19.000000,None,73.000000,77.000000,70.000000,85.000000,220.00,73.33
14,1015.0,Nikhil,21.000000,Dharwad,72.000000,75.000000,76.000000,84.000000,223.00,74.33
20,1021.0,Manoj,19.444444,Tumakuru,70.000000,72.000000,74.000000,82.000000,216.00,72.00
4,1005.0,Rohan,19.000000,Mangaluru,69.000000,71.000000,73.000000,81.000000,213.00,71.00
12,1013.0,Rahul,20.000000,Bengaluru,67.000000,69.000000,71.000000,79.000000,207.00,69.00

In [550]:
df['python_marks'].mean().round(2)

np.float64(82.71)

In [551]:
# Add a new column called total_marks.
df['total_marks']=(df['pandas_marks']+df['python_marks']+df['sql_marks']).round(2)

In [552]:
df

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks,average_marks
0,1001.0,Aarav,18.000000,Mysuru,85.000000,82.000000,88.000000,92.000000,255.00,85.00
1,1002.0,Diya,19.000000,Bengaluru,92.000000,89.000000,94.000000,96.000000,275.00,91.67
2,1003.0,Arjun,18.000000,Dharwad,76.000000,74.000000,79.000000,88.000000,229.00,76.33
3,1004.0,Ananya,20.000000,Belagavi,82.740741,91.000000,85.000000,94.000000,258.74,86.25
4,1005.0,Rohan,19.000000,Mangaluru,69.000000,71.000000,73.000000,81.000000,213.00,71.00
5,1006.0,Ishita,18.000000,Hubballi,95.000000,93.000000,96.000000,98.000000,284.00,94.67
6,1007.0,Vivek,21.000000,Mysuru,81.000000,79.000000,84.000000,90.000000,244.00,81.33
7,1008.0,Sneha,19.000000,None,73.000000,77.000000,70.000000,85.000000,220.00,73.33
8,1009.0,Karan,20.000000,Shivamogga,90.000000,88.000000,92.000000,95.000000,270.00,90.00
9,1010.0,Meera,18.000000,Udupi,84.000000,86.000000,87.000000,91.000000,257.00,85.67
10,1011.0,Aditya,22.000000,Tumakuru,78.000000,81.000000,80.000000,87.000000,239.00,79.67
11,1012.0,Pooja,19.000000,Mysuru,91.000000,82.307692,93.000000,97.000000,266.31,88.77
12,1013.0,Rahul,20.000000,Bengaluru,67.000000,69.000000,71.000000,79.000000,207.00,69.00
13,1014.0,Kavya,18.000000,Belagavi,86.000000,84.000000,89.000000,93.000000,259.00,86.33
14,1015.0,Nikhil,21.000000,Dharwad,72.000000,75.000000,76.000000,84.000000,223.00,74.33
15,1016.0,Priya,19.000000,Mangaluru,94.000000,92.000000,91.000000,96.000000,277.00,92.33
16,1017.0,Sanjay,22.000000,Hubballi,80.000000,78.000000,82.000000,90.592593,240.00,80.00
17,1018.0,Neha,20.000000,Mysuru,75.000000,73.000000,78.000000,86.000000,226.00,75.33
18,1019.0,Varun,18.000000,Udupi,89.000000,91.000000,90.000000,94.000000,270.00,90.00
19,1020.0,Aisha,21.000000,Bengaluru,83.000000,85.000000,88.000000,90.000000,256.00,85.33
20,1021.0,Manoj,19.444444,Tumakuru,70.000000,72.000000,74.000000,82.000000,216.00,72.00
21,1022.0,Riya,20.000000,Shivamogga,96.000000,94.000000,95.000000,99.000000,285.00,95.00
22,1023.0,Akash,18.000000,Belagavi,87.000000,88.000000,85.000000,92.000000,260.00,86.67
23,1024.0,Shreya,22.000000,Mangaluru,79.000000,76.000000,84.740741,88.000000,239.74,79.91
24,1025.0,Yash,19.000000,Mysuru,93.000000,90.000000,92.000000,97.000000,275.00,91.67
28,NaN,None,19.444444,None,82.740741,82.307692,84.740741,90.592593,249.79,83.26

In [553]:
# sql marks >90 and python marks>90
df[(df['sql_marks']>90) & (df['python_marks']>90)]

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks,average_marks
5,1006.0,Ishita,18.0,Hubballi,95.0,93.0,96.0,98.0,284.0,94.67
15,1016.0,Priya,19.0,Mangaluru,94.0,92.0,91.0,96.0,277.0,92.33
21,1022.0,Riya,20.0,Shivamogga,96.0,94.0,95.0,99.0,285.0,95.00

In [554]:
df.query("python_marks>90 and city=='Hubballi'")

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks,average_marks
5,1006.0,Ishita,18.0,Hubballi,95.0,93.0,96.0,98.0,284.0,94.67